[2023-12-16 07:25:10,982] [views.py:338] [views:updata_information] [INFO]- {'pid': '11', 'pdName': '222', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '1', 'kddh': 'YT2505682327311'}
[2023-12-16 07:25:17,293] [views.py:338] [views:updata_information] [INFO]- {'pid': '11', 'pdName': '222', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '1', 'kddh': 'YT2505682327311'}
[2023-12-16 07:27:04,383] [views.py:338] [views:updata_information] [INFO]- {'pid': '11', 'pdName': '222', 'purchasePlatform': '1', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '1', 'kddh': 'YT2505682327311'}
[2023-12-16 07:27:45,327] [views.py:224] [views:add_index] [INFO]- {'pid': '1702711665341', 'pdName': '22222', 'purchasePlatform': '1', 'buyDate': '2023.12.01', 'goonDate': '2023.12.01', 'expectDate': '2023.12.01', 'price': '33333', 'sellprice': '4444444', 'purchaseState': '1', 'kddh': '12456'}
[2023-12-16 07:46:58,062] [views.py:338] [views:updata_information] [INFO]- {'pid': '2', 'pdName': 'huawei', 'purchasePlatform': 'NaN', 'buyDate': '1610162400000', 'goonDate': '1674963000000', 'expectDate': '1705846800000', 'price': '1999', 'sellprice': '2999', 'purchaseState': '已结算', 'kddh': '9856768075519'}
[2023-12-16 07:47:04,516] [views.py:338] [views:updata_information] [INFO]- {'pid': '2', 'pdName': 'huawei', 'purchasePlatform': '1', 'buyDate': '1610162400000', 'goonDate': '1674963000000', 'expectDate': '1705846800000', 'price': '1999', 'sellprice': '2999', 'purchaseState': '1', 'kddh': '9856768075519'}
[2023-12-16 07:47:18,812] [views.py:338] [views:updata_information] [INFO]- {'pid': '2', 'pdName': 'huawei', 'purchasePlatform': '1', 'buyDate': '1610162400000', 'goonDate': '1674963000000', 'expectDate': '1705846800000', 'price': '1999', 'sellprice': '2999', 'purchaseState': '1', 'kddh': '9856768075519'}
[2023-12-16 07:50:39,809] [views.py:224] [views:add_index] [INFO]- {'pid': '1702713039826', 'pdName': '222', 'purchasePlatform': '0', 'buyDate': '2024.01.01 22:20', 'goonDate': '2024.01.01 22:20', 'expectDate': '2024.01.01 22:20', 'price': '222', 'sellprice': '222', 'purchaseState': '0', 'kddh': '2444'}
[2023-12-16 07:50:44,021] [views.py:224] [views:add_index] [INFO]- {'pid': '1702713044040', 'pdName': '222888', 'purchasePlatform': '0', 'buyDate': '2024.01.01 22:20', 'goonDate': '2024.01.01 22:20', 'expectDate': '2024.01.01 22:20', 'price': '222', 'sellprice': '222', 'purchaseState': '0', 'kddh': '2444'}
[2023-12-16 07:59:47,453] [views.py:224] [views:add_index] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721039'}
[2023-12-16 07:59:51,205] [views.py:224] [views:add_index] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721032'}
[2023-12-16 08:00:31,029] [views.py:224] [views:add_index] [INFO]- {'pid': '1792713944049', 'pdName': '123', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721032'}
[2023-12-16 08:00:38,242] [views.py:224] [views:add_index] [INFO]- {'pid': '1792713944040', 'pdName': '123', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721032'}
[2023-12-16 08:00:41,998] [views.py:224] [views:add_index] [INFO]- {'pid': '17927139442222', 'pdName': '123', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721032'}
[2023-12-16 08:00:50,562] [views.py:224] [views:add_index] [INFO]- {'pid': '17927139442222', 'pdName': '98218', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721032'}
[2023-12-16 08:00:56,566] [views.py:224] [views:add_index] [INFO]- {'pid': '17927139442222', 'pdName': '98218', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721033'}
[2023-12-16 08:01:09,198] [views.py:224] [views:add_index] [INFO]- {'pid': '1702713669223', 'pdName': '444', 'purchasePlatform': '3', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '4444', 'sellprice': '4444', 'purchaseState': '1', 'kddh': '444444'}
[2023-12-16 08:01:59,435] [views.py:224] [views:add_index] [INFO]- {'pid': '1702713719461', 'pdName': '444', 'purchasePlatform': '3', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '4444', 'sellprice': '4444', 'purchaseState': '1', 'kddh': 'JDX021297721038'}
[2023-12-16 08:03:12,979] [views.py:224] [views:add_index] [INFO]- {'pid': '17927139442222', 'pdName': '98218', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': '1444'}
[2023-12-16 08:03:18,618] [views.py:224] [views:add_index] [INFO]- {'pid': '179271392', 'pdName': '9821833', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': '1444'}
[2023-12-16 08:03:44,385] [views.py:224] [views:add_index] [INFO]- {'pid': '1702713824412', 'pdName': '33333', 'purchasePlatform': '1', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '444', 'sellprice': '4444', 'purchaseState': '1', 'kddh': 'JDX021297721099'}
[2023-12-16 08:05:30,973] [views.py:224] [views:add_index] [INFO]- {'pid': '1702713931000', 'pdName': '哟与有', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '222', 'sellprice': '22222', 'purchaseState': '1', 'kddh': 'JDX021297721039'}
[2023-12-16 08:05:35,535] [views.py:224] [views:add_index] [INFO]- {'pid': '1702713935562', 'pdName': '哟与有', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '222', 'sellprice': '22222', 'purchaseState': '1', 'kddh': 'JDX021297721035'}
[2023-12-16 08:26:01,948] [views.py:111] [views:gtimg] [INFO]- 验证码:HG[5
[2023-12-16 08:26:09,480] [views.py:111] [views:gtimg] [INFO]- 验证码:MVU0
[2023-12-16 08:26:18,575] [views.py:111] [views:gtimg] [INFO]- 验证码:SY8P
[2023-12-16 08:26:19,928] [views.py:111] [views:gtimg] [INFO]- 验证码:6AA5
[2023-12-16 08:26:20,090] [views.py:111] [views:gtimg] [INFO]- 验证码:3E1M
[2023-12-16 08:26:20,417] [views.py:111] [views:gtimg] [INFO]- 验证码:B4Y5
[2023-12-16 08:26:20,576] [views.py:111] [views:gtimg] [INFO]- 验证码:3923
[2023-12-16 08:27:25,153] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:70', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-16 08:27:31,689] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:00', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-16 08:27:36,907] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:00', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-16 08:27:37,641] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:00', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-16 08:27:37,912] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:00', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-16 08:27:38,109] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:00', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-16 08:27:45,601] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702713719461', 'pdName': '444', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '4444', 'sellprice': '4444', 'purchaseState': '已结算', 'kddh': 'JDX021297721038'}
[2023-12-16 08:27:56,124] [views.py:338] [views:updata_information] [INFO]- {'pid': '1', 'pdName': '华为mete60Pro', 'purchasePlatform': '1', 'buyDate': '2021.01.03 11:20', 'goonDate': '2023.01.31 11:30', 'expectDate': '2024.01.01 22:20', 'price': '222', 'sellprice': '2999', 'purchaseState': '1', 'kddh': 'JDVA22700417677'}
[2023-12-16 08:28:03,858] [views.py:338] [views:updata_information] [INFO]- {'pid': '1', 'pdName': '华为mete60Pro', 'purchasePlatform': '1', 'buyDate': '2021.01.03 11:20', 'goonDate': '2023.01.31 11:30', 'expectDate': '2024.01.01 22:20', 'price': '222', 'sellprice': '2999', 'purchaseState': '1', 'kddh': 'JDVA22700417677'}
[2023-12-16 08:29:14,504] [views.py:224] [views:add_index] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '0', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '1', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:22,429] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '1', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:36,552] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '2', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:47,546] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '3', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:48,828] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': '1', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': 'JDX021297721032'}
[2023-12-16 08:29:54,203] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '3', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:54,601] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '3', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:54,788] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '3', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:54,978] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '3', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 08:29:55,140] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702715355017', 'pdName': '阿迪达斯', 'purchasePlatform': '3', 'buyDate': '2023.12.16 11:11', 'goonDate': '2023.12.16 11:11', 'expectDate': '2023.12.16 11:11', 'price': '2666', 'sellprice': '3666', 'purchaseState': '已结算', 'kddh': 'JDX021566405633'}
[2023-12-16 10:09:40,354] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': 'NaN', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-16 10:09:49,942] [views.py:338] [views:updata_information] [INFO]- {'pid': '123', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '已结算', 'kddh': 'JDX021297721032'}
[2023-12-18 02:49:38,918] [views.py:111] [views:gtimg] [INFO]- 验证码:040Q
[2023-12-18 02:53:04,314] [views.py:224] [views:add_index] [INFO]- {'pid': '1702867986013', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '2', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '185', 'sellprice': '205', 'purchaseState': '0', 'kddh': 'JDX021566405633'}
[2023-12-18 02:53:06,717] [views.py:224] [views:add_index] [INFO]- {'pid': '1702867988433', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '2', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '185', 'sellprice': '205', 'purchaseState': '0', 'kddh': 'JDX021566405633'}
[2023-12-18 02:54:39,919] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868081617', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '2', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '185', 'sellprice': '205', 'purchaseState': '0', 'kddh': 'JDX021566405633'}
[2023-12-18 02:55:40,341] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868142028', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '2', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '185', 'sellprice': '205', 'purchaseState': '0', 'kddh': 'JDX021566405633'}
[2023-12-18 02:55:50,992] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868152688', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '2', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '185', 'sellprice': '205', 'purchaseState': '0', 'kddh': 'JDX021566405622'}
[2023-12-18 02:58:18,996] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868300702', 'pdName': 'adidas休闲羽绒服 HG8751', 'purchasePlatform': '2', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '362.55', 'sellprice': '384.36', 'purchaseState': '0', 'kddh': 'JDX021030924355'}
[2023-12-18 02:58:25,076] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868306768', 'pdName': 'adidas休闲羽绒服 HG8751', 'purchasePlatform': '2', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '362.55', 'sellprice': '384.36', 'purchaseState': '0', 'kddh': 'JDX021030924355'}
[2023-12-18 02:58:38,040] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868319727', 'pdName': 'adidas休闲羽绒服 HG8751', 'purchasePlatform': '2', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '363', 'sellprice': '384', 'purchaseState': '0', 'kddh': 'JDX021030924355'}
[2023-12-18 02:58:44,398] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868326083', 'pdName': 'adidas休闲羽绒服 HG8751', 'purchasePlatform': '2', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '363', 'sellprice': '384', 'purchaseState': '0', 'kddh': 'JDX021030924354'}
[2023-12-18 03:04:45,923] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '0', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '162', 'purchaseState': '0', 'kddh': 'JDK003306888524'}
[2023-12-18 03:04:45,983] [views.py:224] [views:add_index] [INFO]- {'pid': '1702868687668', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '0', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '162', 'purchaseState': '0', 'kddh': 'JDK003306888524'}
[2023-12-18 03:26:26,755] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '162', 'purchaseState': '未结算', 'kddh': 'JDK003306888524'}
[2023-12-18 03:28:51,235] [views.py:224] [views:add_index] [INFO]- {'pid': '1702870132907', 'pdName': 'NIKEAIR 低帮棕色男女同款 FZ7372-200', 'purchasePlatform': '2', 'buyDate': '2023.12.09 21:15', 'goonDate': '2023.12.09 21:15', 'expectDate': '2023.12.09 21:15', 'price': '699', 'sellprice': '704', 'purchaseState': '0', 'kddh': 'zanshimeiy'}
[2023-12-18 03:29:09,615] [views.py:224] [views:add_index] [INFO]- {'pid': '1702870151324', 'pdName': 'NIKEAIR 低帮棕色男女同款 FZ7372-200', 'purchasePlatform': '2', 'buyDate': '2023.12.09 21:15', 'goonDate': '2023.12.09 21:15', 'expectDate': '2023.12.09 21:15', 'price': '699', 'sellprice': '704', 'purchaseState': '0', 'kddh': 'jd22222222'}
[2023-12-18 03:29:16,280] [views.py:224] [views:add_index] [INFO]- {'pid': '1702870157975', 'pdName': 'NIKEAIR 低帮棕色男女同款 FZ7372-200', 'purchasePlatform': '2', 'buyDate': '2023.12.09 21:15', 'goonDate': '2023.12.09 21:15', 'expectDate': '2023.12.09 21:15', 'price': '699', 'sellprice': '704', 'purchaseState': '0', 'kddh': 'jd22222222222'}
[2023-12-18 03:33:45,173] [views.py:224] [views:add_index] [INFO]- {'pid': '1702870426875', 'pdName': '361big3篮球白紫色 672331109', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.16 00:00', 'expectDate': '2023.12.16 00:00', 'price': '144', 'sellprice': '169', 'purchaseState': '0', 'kddh': 'jdx222222222'}
[2023-12-18 05:49:20,262] [views.py:111] [views:gtimg] [INFO]- 验证码:GST3
[2023-12-18 05:49:41,260] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2023-12-18 06:13:51,155] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880032864', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.1.1 01:01', 'goonDate': '2023.1.1 01:01', 'expectDate': '2023.1.1 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:13:58,016] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880039783', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.1.1 01:01', 'goonDate': '2023.1.1 01:01', 'expectDate': '2023.1.1 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:13:58,111] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880039827', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.1.1 01:01', 'goonDate': '2023.1.1 01:01', 'expectDate': '2023.1.1 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:14:09,876] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880051612', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:14:10,197] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880051971', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:14:10,413] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880052147', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:14:10,554] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880052308', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:14:10,714] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880052464', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx000000000'}
[2023-12-18 06:14:23,408] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880065148', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx0000000000'}
[2023-12-18 06:14:23,638] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880065407', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx0000000000'}
[2023-12-18 06:14:23,825] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880065565', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jsx0000000000'}
[2023-12-18 06:14:35,334] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880077088', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jdx0000000000'}
[2023-12-18 06:14:35,491] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880077255', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jdx0000000000'}
[2023-12-18 06:14:35,665] [views.py:224] [views:add_index] [INFO]- {'pid': '1702880077407', 'pdName': '123', 'purchasePlatform': '0', 'buyDate': '2023.01.01 01:01', 'goonDate': '2023.01.01 01:01', 'expectDate': '2023.01.01 01:01', 'price': '11', 'sellprice': '11', 'purchaseState': '0', 'kddh': 'jdx0000000000'}
[2023-12-18 10:26:43,981] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-18 10:36:44,093] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-18 10:56:44,192] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-18 11:26:44,287] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 07:56:31,286] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 08:06:31,824] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 08:26:31,913] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 08:56:32,008] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 10:31:23,702] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 10:33:24,212] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 10:41:24,132] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 10:43:24,309] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:01:24,238] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:03:24,424] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:31:24,336] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:33:24,525] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:43:27,899] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:45:28,069] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:53:28,657] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:55:29,298] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:13:28,816] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:15:29,468] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:43:29,517] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:45:29,575] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 10:53:33,729] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 10:55:33,753] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:03:33,845] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:05:33,855] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:23:33,976] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:25:33,949] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:49:04,194] [views.py:111] [views:gtimg] [INFO]- 验证码:G773
[2023-12-21 11:51:20,984] [views.py:111] [views:gtimg] [INFO]- 验证码:9T7G
[2023-12-21 11:53:34,067] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:55:34,123] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 14:25:07,275] [views.py:111] [views:gtimg] [INFO]- 验证码:2Z92
[2023-12-21 21:45:15,717] [views.py:111] [views:gtimg] [INFO]- 验证码:OIWN
[2023-12-21 23:13:09,790] [views.py:111] [views:gtimg] [INFO]- 验证码:G4ZZ
[2023-12-21 23:28:30,730] [views.py:111] [views:gtimg] [INFO]- 验证码:2286
[2023-12-21 23:43:18,346] [views.py:111] [views:gtimg] [INFO]- 验证码:CPDY
[2023-12-22 00:58:14,980] [views.py:111] [views:gtimg] [INFO]- 验证码:SQ7D
[2023-12-22 01:13:22,538] [views.py:111] [views:gtimg] [INFO]- 验证码:39PX
[2023-12-22 03:22:33,326] [views.py:111] [views:gtimg] [INFO]- 验证码:UAAN
[2023-12-22 03:53:58,968] [views.py:111] [views:gtimg] [INFO]- 验证码:1E8Z
[2023-12-22 04:18:39,201] [views.py:111] [views:gtimg] [INFO]- 验证码:Q33E
[2023-12-22 04:33:44,484] [views.py:111] [views:gtimg] [INFO]- 验证码:Q1IV
[2023-12-22 05:54:29,396] [views.py:111] [views:gtimg] [INFO]- 验证码:I74R
[2023-12-22 06:09:48,255] [views.py:111] [views:gtimg] [INFO]- 验证码:59WR
[2023-12-22 06:10:18,668] [views.py:111] [views:gtimg] [INFO]- 验证码:S5W5
[2023-12-22 11:05:42,537] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 11:15:42,639] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 11:35:42,728] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 12:05:42,819] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 13:53:51,707] [views.py:111] [views:gtimg] [INFO]- 验证码:ERHR
[2023-12-22 20:20:19,122] [views.py:111] [views:gtimg] [INFO]- 验证码:UPV2
[2023-12-23 00:40:03,937] [views.py:111] [views:gtimg] [INFO]- 验证码:885J
[2023-12-23 01:44:34,529] [views.py:111] [views:gtimg] [INFO]- 验证码:Y2TP
[2023-12-23 09:00:55,696] [views.py:111] [views:gtimg] [INFO]- 验证码:47SB
[2023-12-23 11:11:26,812] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:13:26,785] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:21:26,906] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:23:26,882] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:41:26,992] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:43:26,977] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 12:11:27,084] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 12:13:27,075] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 17:01:13,492] [views.py:111] [views:gtimg] [INFO]- 验证码:V1M7
[2023-12-23 18:05:40,652] [views.py:111] [views:gtimg] [INFO]- 验证码:6X5H
[2023-12-23 19:54:35,212] [views.py:111] [views:gtimg] [INFO]- 验证码:69Y0
[2023-12-23 20:18:41,888] [views.py:111] [views:gtimg] [INFO]- 验证码:B7U5
[2023-12-24 04:56:11,085] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/v1/auth/captcha
[2023-12-24 04:56:13,576] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/v1/auth/captcha
[2023-12-24 05:08:48,099] [views.py:111] [views:gtimg] [INFO]- 验证码:7OG6
[2023-12-24 05:08:51,448] [views.py:111] [views:gtimg] [INFO]- 验证码:8HGI
[2023-12-24 05:09:02,600] [views.py:111] [views:gtimg] [INFO]- 验证码:KN39
[2023-12-24 05:10:01,970] [views.py:111] [views:gtimg] [INFO]- 验证码:K29Y
[2023-12-24 05:10:13,847] [views.py:111] [views:gtimg] [INFO]- 验证码:5HH7
[2023-12-24 05:12:17,355] [views.py:111] [views:gtimg] [INFO]- 验证码:UX59
[2023-12-24 05:12:24,624] [views.py:111] [views:gtimg] [INFO]- 验证码:PQA9
[2023-12-24 05:13:35,304] [views.py:111] [views:gtimg] [INFO]- 验证码:LR9M
[2023-12-24 05:13:50,984] [views.py:111] [views:gtimg] [INFO]- 验证码:[5G1
[2023-12-24 05:13:53,911] [views.py:111] [views:gtimg] [INFO]- 验证码:G1P9
[2023-12-24 05:14:02,965] [views.py:111] [views:gtimg] [INFO]- 验证码:8J9S
[2023-12-24 05:14:04,022] [views.py:111] [views:gtimg] [INFO]- 验证码:[B67
[2023-12-24 05:14:08,051] [views.py:111] [views:gtimg] [INFO]- 验证码:4OCW
[2023-12-24 05:14:29,306] [views.py:111] [views:gtimg] [INFO]- 验证码:B932
[2023-12-24 05:17:00,298] [views.py:111] [views:gtimg] [INFO]- 验证码:L6YD
[2023-12-24 05:17:02,647] [views.py:111] [views:gtimg] [INFO]- 验证码:83EG
[2023-12-24 05:17:23,954] [views.py:111] [views:gtimg] [INFO]- 验证码:SUU1
[2023-12-24 05:17:28,183] [views.py:111] [views:gtimg] [INFO]- 验证码:8SL1
[2023-12-24 05:18:08,716] [views.py:111] [views:gtimg] [INFO]- 验证码:42M8
[2023-12-24 05:18:17,955] [views.py:111] [views:gtimg] [INFO]- 验证码:E4E4
[2023-12-24 05:18:31,269] [views.py:111] [views:gtimg] [INFO]- 验证码:NF5R
[2023-12-24 05:18:37,703] [views.py:111] [views:gtimg] [INFO]- 验证码:6C4T
[2023-12-24 05:19:02,676] [views.py:111] [views:gtimg] [INFO]- 验证码:1O23
[2023-12-24 05:19:15,041] [views.py:111] [views:gtimg] [INFO]- 验证码:S40S
[2023-12-24 05:19:42,039] [views.py:111] [views:gtimg] [INFO]- 验证码:CJML
[2023-12-24 05:19:48,960] [views.py:111] [views:gtimg] [INFO]- 验证码:GI3U
[2023-12-24 05:19:53,599] [views.py:111] [views:gtimg] [INFO]- 验证码:C7F1
[2023-12-24 05:20:10,975] [views.py:111] [views:gtimg] [INFO]- 验证码:S38U
[2023-12-24 05:20:28,494] [views.py:111] [views:gtimg] [INFO]- 验证码:7ZOI
[2023-12-24 05:20:37,962] [views.py:111] [views:gtimg] [INFO]- 验证码:67[9
[2023-12-24 05:21:07,475] [views.py:111] [views:gtimg] [INFO]- 验证码:ZG1J
[2023-12-24 05:23:31,772] [views.py:111] [views:gtimg] [INFO]- 验证码:67XD
[2023-12-24 05:23:34,440] [views.py:111] [views:gtimg] [INFO]- 验证码:H280
[2023-12-24 05:23:39,446] [views.py:111] [views:gtimg] [INFO]- 验证码:8T2F
[2023-12-24 05:24:25,884] [views.py:111] [views:gtimg] [INFO]- 验证码:749K
[2023-12-24 05:25:41,728] [views.py:111] [views:gtimg] [INFO]- 验证码:UPOI
[2023-12-24 05:25:44,377] [views.py:111] [views:gtimg] [INFO]- 验证码:W4D4
[2023-12-24 05:27:09,222] [views.py:111] [views:gtimg] [INFO]- 验证码:H9JN
[2023-12-24 05:27:13,714] [views.py:111] [views:gtimg] [INFO]- 验证码:4B45
[2023-12-24 05:28:17,849] [views.py:111] [views:gtimg] [INFO]- 验证码:T23U
[2023-12-24 05:32:44,292] [views.py:111] [views:gtimg] [INFO]- 验证码:767O
[2023-12-24 05:34:51,690] [views.py:111] [views:gtimg] [INFO]- 验证码:6EM2
[2023-12-24 05:35:50,917] [views.py:111] [views:gtimg] [INFO]- 验证码:5L9O
[2023-12-24 05:35:57,118] [views.py:111] [views:gtimg] [INFO]- 验证码:4424
[2023-12-24 05:36:09,534] [views.py:111] [views:gtimg] [INFO]- 验证码:OO12
[2023-12-24 05:36:52,856] [views.py:111] [views:gtimg] [INFO]- 验证码:P834
[2023-12-24 05:44:13,406] [views.py:111] [views:gtimg] [INFO]- 验证码:4O7G
[2023-12-24 05:44:36,988] [views.py:111] [views:gtimg] [INFO]- 验证码:0X8[
[2023-12-24 05:44:42,220] [views.py:111] [views:gtimg] [INFO]- 验证码:E88W
[2023-12-24 05:45:34,350] [views.py:111] [views:gtimg] [INFO]- 验证码:SG9W
[2023-12-24 05:45:38,821] [views.py:111] [views:gtimg] [INFO]- 验证码:076H
[2023-12-24 05:46:00,922] [views.py:111] [views:gtimg] [INFO]- 验证码:WF29
[2023-12-24 05:46:05,609] [views.py:111] [views:gtimg] [INFO]- 验证码:70L2
[2023-12-24 05:46:06,904] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/api/testlogin
[2023-12-24 05:46:18,216] [views.py:111] [views:gtimg] [INFO]- 验证码:R7Y[
[2023-12-24 05:46:20,946] [views.py:111] [views:gtimg] [INFO]- 验证码:T3E9
[2023-12-24 05:50:04,387] [views.py:111] [views:gtimg] [INFO]- 验证码:JW6X
[2023-12-24 05:50:41,082] [views.py:111] [views:gtimg] [INFO]- 验证码:3GSF
[2023-12-24 05:50:55,245] [views.py:111] [views:gtimg] [INFO]- 验证码:9YS5
[2023-12-24 05:51:36,938] [views.py:111] [views:gtimg] [INFO]- 验证码:DZ92
[2023-12-24 05:52:01,915] [views.py:111] [views:gtimg] [INFO]- 验证码:GK6S
[2023-12-24 05:52:28,333] [views.py:111] [views:gtimg] [INFO]- 验证码:BMMT
[2023-12-24 05:52:41,648] [views.py:111] [views:gtimg] [INFO]- 验证码:3Y7B
[2023-12-24 05:52:55,578] [views.py:111] [views:gtimg] [INFO]- 验证码:UOH1
[2023-12-24 05:52:58,069] [views.py:111] [views:gtimg] [INFO]- 验证码:4Y4B
[2023-12-24 05:53:34,754] [views.py:111] [views:gtimg] [INFO]- 验证码:HGJU
[2023-12-24 05:54:00,500] [views.py:111] [views:gtimg] [INFO]- 验证码:4AWC
[2023-12-24 05:54:03,818] [views.py:111] [views:gtimg] [INFO]- 验证码:0HON
[2023-12-24 05:55:56,286] [views.py:111] [views:gtimg] [INFO]- 验证码:[5VZ
[2023-12-24 05:55:59,242] [views.py:111] [views:gtimg] [INFO]- 验证码:LBJ1
[2023-12-24 06:38:08,847] [views.py:111] [views:gtimg] [INFO]- 验证码:XNW9
[2023-12-24 07:11:21,745] [views.py:111] [views:gtimg] [INFO]- 验证码:QWCS
[2023-12-24 07:27:21,190] [views.py:111] [views:gtimg] [INFO]- 验证码:PQZK
[2023-12-24 09:53:35,266] [views.py:111] [views:gtimg] [INFO]- 验证码:WM4V
[2023-12-24 11:21:49,628] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 11:31:49,780] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 11:51:49,870] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 12:21:49,965] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 13:33:04,327] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-24 13:43:04,437] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-24 14:03:04,531] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-24 14:25:18,493] [views.py:111] [views:gtimg] [INFO]- 验证码:ICGB
[2023-12-24 14:28:36,630] [views.py:111] [views:gtimg] [INFO]- 验证码:2O2M
[2023-12-24 14:31:32,471] [views.py:111] [views:gtimg] [INFO]- 验证码:CI39
[2023-12-24 14:32:26,105] [views.py:111] [views:gtimg] [INFO]- 验证码:7831
[2023-12-24 14:33:04,620] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-24 14:37:59,256] [views.py:111] [views:gtimg] [INFO]- 验证码:05LL
[2023-12-24 15:27:52,257] [views.py:111] [views:gtimg] [INFO]- 验证码:9N66
[2023-12-24 16:35:46,796] [views.py:111] [views:gtimg] [INFO]- 验证码:JS50
[2023-12-24 17:17:30,098] [views.py:111] [views:gtimg] [INFO]- 验证码:U34K
[2023-12-24 20:42:31,509] [views.py:111] [views:gtimg] [INFO]- 验证码:8P3H
[2023-12-24 22:46:14,220] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/session/properties
[2023-12-24 23:14:15,705] [views.py:111] [views:gtimg] [INFO]- 验证码:0H7O
[2023-12-24 23:25:13,842] [views.py:111] [views:gtimg] [INFO]- 验证码:6FK0
[2023-12-24 23:56:40,476] [views.py:111] [views:gtimg] [INFO]- 验证码:92EC
[2023-12-25 00:26:30,057] [views.py:111] [views:gtimg] [INFO]- 验证码:1D4Q
[2023-12-25 00:58:43,541] [views.py:111] [views:gtimg] [INFO]- 验证码:OYVW
[2023-12-25 01:07:44,152] [views.py:111] [views:gtimg] [INFO]- 验证码:3H17
[2023-12-25 01:13:50,738] [views.py:111] [views:gtimg] [INFO]- 验证码:K1HH
[2023-12-25 03:21:46,648] [views.py:111] [views:gtimg] [INFO]- 验证码:9P99
[2023-12-25 06:02:10,407] [views.py:111] [views:gtimg] [INFO]- 验证码:3E4B
[2023-12-25 06:25:40,404] [views.py:111] [views:gtimg] [INFO]- 验证码:1RPS
[2023-12-25 06:36:09,353] [views.py:111] [views:gtimg] [INFO]- 验证码:9O5K
[2023-12-25 08:30:44,518] [views.py:111] [views:gtimg] [INFO]- 验证码:0M9C
[2023-12-25 08:45:35,706] [views.py:111] [views:gtimg] [INFO]- 验证码:2FNQ
[2023-12-25 08:54:25,213] [views.py:111] [views:gtimg] [INFO]- 验证码:L271
[2023-12-25 10:36:37,476] [views.py:111] [views:gtimg] [INFO]- 验证码:F51P
[2023-12-25 11:24:31,535] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-25 11:34:31,651] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-25 11:54:31,748] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-25 12:24:31,863] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-25 12:30:26,479] [views.py:111] [views:gtimg] [INFO]- 验证码:QX8T
[2023-12-25 13:59:35,015] [views.py:111] [views:gtimg] [INFO]- 验证码:WF1V
[2023-12-25 14:09:28,551] [views.py:111] [views:gtimg] [INFO]- 验证码:66FS
[2023-12-25 14:52:19,124] [views.py:111] [views:gtimg] [INFO]- 验证码:9F0V
[2023-12-25 15:46:45,399] [views.py:111] [views:gtimg] [INFO]- 验证码:ZCYW
[2023-12-25 16:59:23,726] [views.py:111] [views:gtimg] [INFO]- 验证码:QI50
[2023-12-25 17:35:30,512] [views.py:111] [views:gtimg] [INFO]- 验证码:I14I
[2023-12-25 17:44:59,994] [views.py:111] [views:gtimg] [INFO]- 验证码:0KYK
[2023-12-25 18:05:30,721] [views.py:111] [views:gtimg] [INFO]- 验证码:R95Y
[2023-12-25 19:06:10,055] [views.py:111] [views:gtimg] [INFO]- 验证码:BHT2
[2023-12-25 20:00:09,271] [views.py:111] [views:gtimg] [INFO]- 验证码:A223
[2023-12-25 20:37:00,356] [views.py:111] [views:gtimg] [INFO]- 验证码:87X7
[2023-12-25 21:20:10,595] [views.py:111] [views:gtimg] [INFO]- 验证码:0GG2
[2023-12-25 22:40:29,065] [views.py:111] [views:gtimg] [INFO]- 验证码:UD8E
[2023-12-26 01:29:32,621] [views.py:111] [views:gtimg] [INFO]- 验证码:61AO
[2023-12-26 02:29:22,177] [views.py:111] [views:gtimg] [INFO]- 验证码:42O0
[2023-12-26 02:43:48,090] [views.py:111] [views:gtimg] [INFO]- 验证码:1448
[2023-12-26 04:40:34,274] [views.py:111] [views:gtimg] [INFO]- 验证码:7B1K
[2023-12-26 04:51:38,187] [views.py:111] [views:gtimg] [INFO]- 验证码:508P
[2023-12-26 05:58:38,077] [views.py:111] [views:gtimg] [INFO]- 验证码:0994
[2023-12-26 06:12:05,599] [views.py:111] [views:gtimg] [INFO]- 验证码:31WH
[2023-12-26 07:35:40,051] [views.py:111] [views:gtimg] [INFO]- 验证码:5U0D
[2023-12-26 08:41:04,570] [views.py:338] [views:updata_information] [INFO]- {'pid': '1702868152688', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': 'NaN', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '185', 'sellprice': '205', 'purchaseState': '未结算', 'kddh': 'JDX021566405622'}
[2023-12-26 09:19:34,159] [views.py:111] [views:gtimg] [INFO]- 验证码:90PC
[2023-12-26 09:38:51,494] [views.py:111] [views:gtimg] [INFO]- 验证码:BY97
[2023-12-26 11:28:07,548] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:30:04,114] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:38:07,650] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:40:04,217] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:44:10,332] [views.py:111] [views:gtimg] [INFO]- 验证码:QU46
[2023-12-26 11:44:13,396] [views.py:111] [views:gtimg] [INFO]- 验证码:54J9
[2023-12-26 11:46:27,597] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/api/v1/auth/captcha
[2023-12-26 11:46:27,648] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/api/v1/auth/captcha
[2023-12-26 11:58:07,743] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 12:00:04,321] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 12:28:07,837] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 12:30:04,413] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 16:11:33,941] [views.py:111] [views:gtimg] [INFO]- 验证码:I0DQ
[2023-12-27 08:12:11,576] [views.py:111] [views:gtimg] [INFO]- 验证码:IG1D
[2023-12-27 08:27:17,151] [views.py:111] [views:gtimg] [INFO]- 验证码:414C
[2023-12-27 09:21:07,769] [views.py:111] [views:gtimg] [INFO]- 验证码:NDQG
[2023-12-27 09:25:48,710] [views.py:111] [views:gtimg] [INFO]- 验证码:1V2W
[2023-12-27 09:32:29,667] [views.py:111] [views:gtimg] [INFO]- 验证码:MUEE
[2023-12-27 09:36:12,581] [views.py:111] [views:gtimg] [INFO]- 验证码:L2R9
[2023-12-27 09:40:55,066] [views.py:111] [views:gtimg] [INFO]- 验证码:5N8K
[2023-12-27 09:47:36,908] [views.py:111] [views:gtimg] [INFO]- 验证码:XMFL
[2023-12-27 10:12:20,575] [views.py:111] [views:gtimg] [INFO]- 验证码:I0WW
[2023-12-27 10:27:27,136] [views.py:111] [views:gtimg] [INFO]- 验证码:51Q8
[2023-12-27 11:40:34,785] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 11:42:35,137] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 11:50:34,884] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 11:52:35,226] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:10:34,970] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:12:35,316] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:40:35,057] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:42:35,407] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:54:14,795] [views.py:338] [views:updata_information] [INFO]- {'pid': '179271392', 'pdName': '9821833', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': '1444'}
[2023-12-27 12:56:54,358] [views.py:338] [views:updata_information] [INFO]- {'pid': '179271392', 'pdName': '9821833', 'purchasePlatform': '2', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '20999', 'sellprice': '2299', 'purchaseState': '1', 'kddh': '1444'}
