[2023-12-28 10:14:40,216] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:14:43,335] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '222222'}
[2023-12-28 10:14:43,661] [views.py:247] [views:add_index] [INFO]- ''
[2023-12-28 10:14:43,679] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 43
[2023-12-28 10:16:43,879] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-12-28 10:16:44,799] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:17:40,434] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-12-28 10:17:41,432] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:17:45,447] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '222222'}
[2023-12-28 10:17:45,761] [views.py:248] [views:add_index] [INFO]- 添加失败:''
[2023-12-28 10:17:45,777] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 43
[2023-12-28 10:17:59,485] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-12-28 10:18:00,630] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:19:40,878] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-12-28 10:19:41,998] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:19:47,034] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-12-28 10:19:48,205] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:20:02,144] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-12-28 10:20:03,164] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:20:05,794] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '222222'}
[2023-12-28 10:20:06,143] [views.py:247] [views:add_index] [INFO]- 添加失败:''
[2023-12-28 10:20:06,160] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 43
[2023-12-28 10:21:34,080] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-12-28 10:21:35,114] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:21:43,326] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '222222'}
[2023-12-28 10:21:43,680] [views.py:247] [views:add_index] [INFO]- 添加失败:''
[2023-12-28 10:21:43,806] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 43
[2023-12-28 10:22:00,928] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-12-28 10:22:02,003] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:22:06,116] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '222222'}
[2023-12-28 10:22:06,429] [views.py:247] [views:add_index] [INFO]- 添加失败:''
[2023-12-28 10:22:06,447] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 43
[2023-12-28 10:22:38,395] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-12-28 10:22:39,390] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:22:40,013] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '222222'}
[2023-12-28 10:22:40,287] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 67
[2023-12-28 10:22:43,332] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '222222'}
[2023-12-28 10:22:43,667] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 67
[2023-12-28 10:25:26,912] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-12-28 10:25:28,154] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-12-28 10:30:37,435] [views.py:224] [views:add_index] [INFO]- {'pid': '1703685252853', 'pdName': '333', 'purchasePlatform': '0', 'buyDate': '2023.11.21 16:49', 'goonDate': '2023.11.21 16:49', 'expectDate': '2023.11.21 16:49', 'price': '22231', 'sellprice': '2213', 'purchaseState': '0', 'kddh': '1'}
[2023-12-28 10:30:37,513] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/addmain/ HTTP/1.1" 200 45
[2023-12-28 11:48:53,612] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-28 11:50:54,181] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-28 11:58:53,744] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-28 11:58:54,840] [views.py:224] [views:add_index] [INFO]- {'pid': '1703764734850', 'pdName': '2222', 'purchasePlatform': '0', 'buyDate': '2023.12.05 00:00', 'goonDate': '2023.12.16 00:00', 'expectDate': '2023.12.13 00:00', 'price': '22222', 'sellprice': '2222', 'purchaseState': '0', 'kddh': ' JDX021030924357'}
[2023-12-28 11:59:02,007] [views.py:224] [views:add_index] [INFO]- {'pid': '1703764742025', 'pdName': '2222', 'purchasePlatform': '0', 'buyDate': '2023.12.05 00:00', 'goonDate': '2023.12.16 00:00', 'expectDate': '2023.12.13 00:00', 'price': '22222', 'sellprice': '2222', 'purchaseState': '0', 'kddh': 'JDX021030924357'}
[2023-12-28 12:00:54,278] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-28 12:18:53,839] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-28 12:20:54,371] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-28 12:48:53,941] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-28 12:50:54,476] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 00:28:34,670] [views.py:111] [views:gtimg] [INFO]- 验证码:9897
[2023-12-29 00:30:19,948] [views.py:111] [views:gtimg] [INFO]- 验证码:6440
[2023-12-29 02:55:36,360] [views.py:111] [views:gtimg] [INFO]- 验证码:4LXO
[2023-12-29 11:57:54,404] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 11:59:54,822] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 12:07:54,515] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 12:09:54,915] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 12:25:49,191] [views.py:111] [views:gtimg] [INFO]- 验证码:1LSH
[2023-12-29 12:27:54,606] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 12:29:55,009] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 12:57:54,719] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 12:59:55,098] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-29 13:23:39,449] [views.py:111] [views:gtimg] [INFO]- 验证码:334D
[2023-12-29 14:52:40,605] [views.py:111] [views:gtimg] [INFO]- 验证码:1WF8
[2023-12-29 15:32:28,652] [views.py:111] [views:gtimg] [INFO]- 验证码:2T1S
[2023-12-29 16:00:48,045] [views.py:111] [views:gtimg] [INFO]- 验证码:31UX
[2023-12-29 17:25:35,730] [views.py:111] [views:gtimg] [INFO]- 验证码:9NWB
[2023-12-29 19:37:07,443] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/session/properties
[2023-12-29 22:10:12,936] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/session/properties
[2023-12-30 04:03:09,395] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/sonicos/auth
[2023-12-30 04:03:09,473] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/sonicos/tfa
[2023-12-30 12:06:37,925] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-30 12:16:38,022] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-30 12:36:38,118] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-30 13:06:38,211] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-30 21:29:53,600] [views.py:111] [views:gtimg] [INFO]- 验证码:T1E1
[2023-12-30 22:36:19,334] [views.py:111] [views:gtimg] [INFO]- 验证码:BADH
[2023-12-31 10:52:14,835] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-31 11:02:14,934] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-31 11:22:15,026] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-31 11:52:15,111] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-31 12:10:03,201] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-31 12:20:03,297] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-31 12:40:03,393] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-31 13:10:03,486] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2024-01-01 11:25:26,167] [views.py:111] [views:gtimg] [INFO]- 验证码:C0T1
[2024-01-01 12:19:34,080] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2024-01-01 12:29:34,185] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2024-01-01 12:49:34,274] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2024-01-01 13:19:34,364] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 296, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2024-01-01 16:07:23,320] [views.py:111] [views:gtimg] [INFO]- 验证码:8K74
[2024-01-01 16:14:09,690] [views.py:111] [views:gtimg] [INFO]- 验证码:15TJ
[2024-01-01 16:19:16,662] [views.py:111] [views:gtimg] [INFO]- 验证码:4Q67
[2024-01-02 06:44:16,590] [views.py:111] [views:gtimg] [INFO]- 验证码:J[WC
[2024-01-02 12:28:05,942] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-02 12:38:06,035] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-02 12:58:06,130] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-02 13:28:06,221] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-03 00:59:00,756] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['16'], 'pid': ['1702868152688'], 'pdName': ['鸿星尔克电池熊猫羽绒服 51223401052'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 14:03'], 'goonDate': ['2023.12.24 14:03'], 'expectDate': ['2023.12.18 14:03'], 'price': ['1852'], 'sellPrice': ['2052'], 'kddh': ['JDX021566405622'], 'purchaseState': ['0'], 'sellprice': ['2052']}>
[2024-01-03 00:59:00,759] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868152688', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '1', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '1852', 'sellprice': '2052', 'purchaseState': '0', 'kddh': 'JDX021566405622'}
[2024-01-03 19:34:22,029] [views.py:111] [views:gtimg] [INFO]- 验证码:F805
[2024-01-03 19:40:14,077] [views.py:111] [views:gtimg] [INFO]- 验证码:8D5A
[2024-01-03 19:55:21,788] [views.py:111] [views:gtimg] [INFO]- 验证码:UB8T
[2024-01-03 19:58:17,905] [views.py:111] [views:gtimg] [INFO]- 验证码:2944
[2024-01-03 20:13:25,132] [views.py:111] [views:gtimg] [INFO]- 验证码:6MQ0
[2024-01-03 20:18:03,986] [views.py:111] [views:gtimg] [INFO]- 验证码:EK3V
[2024-01-03 20:18:28,063] [views.py:111] [views:gtimg] [INFO]- 验证码:8O2W
[2024-01-03 20:33:13,276] [views.py:111] [views:gtimg] [INFO]- 验证码:LM8J
[2024-01-03 20:37:00,358] [views.py:111] [views:gtimg] [INFO]- 验证码:Z52D
[2024-01-03 20:57:00,852] [views.py:111] [views:gtimg] [INFO]- 验证码:TJ3J
[2024-01-03 21:07:45,977] [views.py:111] [views:gtimg] [INFO]- 验证码:96[Z
[2024-01-03 21:31:51,165] [views.py:111] [views:gtimg] [INFO]- 验证码:33F7
[2024-01-03 22:13:33,219] [views.py:111] [views:gtimg] [INFO]- 验证码:3PZK
[2024-01-03 22:28:43,170] [views.py:111] [views:gtimg] [INFO]- 验证码:[X7Q
[2024-01-04 00:36:27,495] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-04 00:46:27,605] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-04 01:06:27,691] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-04 01:36:27,783] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 293, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2024-01-04 06:41:05,335] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['16'], 'pid': ['1702868152688'], 'pdName': ['鸿星尔克电池熊猫羽绒服 51223401052'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 14:03'], 'goonDate': ['2023.12.24 14:03'], 'expectDate': ['2023.12.18 14:03'], 'price': ['182'], 'sellPrice': ['202'], 'kddh': ['JDX021566405622'], 'purchaseState': ['0'], 'sellprice': ['202']}>
[2024-01-04 06:41:05,335] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868152688', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '1', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '182', 'sellprice': '202', 'purchaseState': '0', 'kddh': 'JDX021566405622'}
[2024-01-04 06:42:53,556] [views.py:224] [views:add_index] [INFO]- {'pid': '1704350573772', 'pdName': '耐克 女子 FB2269-106 37.5', 'purchasePlatform': '2', 'buyDate': '2024.01.03 00:00', 'goonDate': '2024.01.04 00:00', 'expectDate': '2024.01.04 00:00', 'price': '399', 'sellprice': '0', 'purchaseState': '0', 'kddh': '1'}
[2024-01-04 06:44:31,606] [views.py:224] [views:add_index] [INFO]- {'pid': '1704350671865', 'pdName': '耐克运动鞋 DQ5354-161 37.5', 'purchasePlatform': '2', 'buyDate': '2024.01.03 00:00', 'goonDate': '2024.01.04 00:00', 'expectDate': '2024.01.04 00:00', 'price': '212', 'sellprice': '242', 'purchaseState': '0', 'kddh': 'JDV014069433347'}
[2024-01-04 06:45:19,560] [views.py:224] [views:add_index] [INFO]- {'pid': '1704350719834', 'pdName': 'kappa 卡帕女款 韩国白 37', 'purchasePlatform': '2', 'buyDate': '2024.01.03 00:00', 'goonDate': '2024.01.03 00:00', 'expectDate': '2024.01.03 00:00', 'price': '238', 'sellprice': '0', 'purchaseState': '0', 'kddh': '1'}
[2024-01-04 06:46:41,925] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['21'], 'pid': ['1702870426875'], 'pdName': ['361big3篮球白紫色 672331109'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.16 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['144'], 'sellPrice': ['158'], 'kddh': ['jdx222222222'], 'purchaseState': ['1'], 'sellprice': ['158']}>
[2024-01-04 06:46:41,925] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702870426875', 'pdName': '361big3篮球白紫色 672331109', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.16 00:00', 'expectDate': '2023.12.16 00:00', 'price': '144', 'sellprice': '158', 'purchaseState': '1', 'kddh': 'jdx222222222'}
[2024-01-04 06:47:01,679] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['19'], 'pid': ['1702868687668'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['162'], 'kddh': ['JDK003306888524'], 'purchaseState': ['1'], 'sellprice': ['162']}>
[2024-01-04 06:47:01,680] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687668', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '162', 'purchaseState': '1', 'kddh': 'JDK003306888524'}
[2024-01-04 06:47:30,612] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['18'], 'pid': ['1702868687611'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['155'], 'kddh': ['1'], 'purchaseState': ['0'], 'sellprice': ['155']}>
[2024-01-04 06:47:30,613] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '155', 'purchaseState': '0', 'kddh': '1'}
[2024-01-04 06:47:33,442] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['18'], 'pid': ['1702868687611'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['155'], 'kddh': ['1'], 'purchaseState': ['0'], 'sellprice': ['155']}>
[2024-01-04 06:47:33,442] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '155', 'purchaseState': '0', 'kddh': '1'}
[2024-01-04 06:47:40,645] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['18'], 'pid': ['1702868687611'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['155'], 'kddh': ['1'], 'purchaseState': ['0'], 'sellprice': ['155']}>
[2024-01-04 06:47:40,645] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '155', 'purchaseState': '0', 'kddh': '1'}
[2024-01-04 06:48:09,178] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['16'], 'pid': ['1702868152688'], 'pdName': ['鸿星尔克电池熊猫羽绒服 51223401052'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 14:03'], 'goonDate': ['2023.12.24 14:03'], 'expectDate': ['2023.12.18 14:03'], 'price': ['182'], 'sellPrice': ['205'], 'kddh': ['JDX021566405622'], 'purchaseState': ['0'], 'sellprice': ['205']}>
[2024-01-04 06:48:09,179] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868152688', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '1', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '182', 'sellprice': '205', 'purchaseState': '0', 'kddh': 'JDX021566405622'}
[2024-01-04 06:48:20,775] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['17'], 'pid': ['1702868326083'], 'pdName': ['adidas休闲羽绒服 HG8751'], 'purchasePlatform': ['2'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['363'], 'sellPrice': ['384'], 'kddh': ['JDX021030924354'], 'purchaseState': ['1'], 'sellprice': ['384']}>
[2024-01-04 06:48:20,775] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868326083', 'pdName': 'adidas休闲羽绒服 HG8751', 'purchasePlatform': '2', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '363', 'sellprice': '384', 'purchaseState': '1', 'kddh': 'JDX021030924354'}
[2024-01-04 06:48:24,739] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['16'], 'pid': ['1702868152688'], 'pdName': ['鸿星尔克电池熊猫羽绒服 51223401052'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 14:03'], 'goonDate': ['2023.12.24 14:03'], 'expectDate': ['2023.12.18 14:03'], 'price': ['182'], 'sellPrice': ['205'], 'kddh': ['JDX021566405622'], 'purchaseState': ['1'], 'sellprice': ['205']}>
[2024-01-04 06:48:24,739] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868152688', 'pdName': '鸿星尔克电池熊猫羽绒服 51223401052', 'purchasePlatform': '1', 'buyDate': '2023.12.16 14:03', 'goonDate': '2023.12.24 14:03', 'expectDate': '2023.12.18 14:03', 'price': '182', 'sellprice': '205', 'purchaseState': '1', 'kddh': 'JDX021566405622'}
[2024-01-04 06:48:33,597] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['18'], 'pid': ['1702868687611'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['162'], 'kddh': ['1'], 'purchaseState': ['0'], 'sellprice': ['162']}>
[2024-01-04 06:48:33,598] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '162', 'purchaseState': '0', 'kddh': '1'}
[2024-01-04 06:49:18,396] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['18'], 'pid': ['1702868687611'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['155'], 'kddh': ['0'], 'purchaseState': ['0'], 'sellprice': ['155']}>
[2024-01-04 06:49:18,396] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '155', 'purchaseState': '0', 'kddh': '0'}
[2024-01-04 06:49:22,102] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['18'], 'pid': ['1702868687611'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['155'], 'kddh': ['1'], 'purchaseState': ['0'], 'sellprice': ['155']}>
[2024-01-04 06:49:22,102] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '155', 'purchaseState': '0', 'kddh': '1'}
[2024-01-04 06:49:25,919] [views.py:335] [views:updata_information] [INFO]- <QueryDict: {'id': ['18'], 'pid': ['1702868687611'], 'pdName': ['361big3team米绿色 672331109-2'], 'purchasePlatform': ['1'], 'buyDate': ['2023.12.16 00:00'], 'goonDate': ['2023.12.18 00:00'], 'expectDate': ['2023.12.16 00:00'], 'price': ['155'], 'sellPrice': ['155'], 'kddh': ['1'], 'purchaseState': ['0'], 'sellprice': ['155']}>
[2024-01-04 06:49:25,919] [views.py:343] [views:updata_information] [INFO]- {'pid': '1702868687611', 'pdName': '361big3team米绿色 672331109-2', 'purchasePlatform': '1', 'buyDate': '2023.12.16 00:00', 'goonDate': '2023.12.18 00:00', 'expectDate': '2023.12.16 00:00', 'price': '155', 'sellprice': '155', 'purchaseState': '0', 'kddh': '1'}
